src/conf/urls.py
import django
import sys
print (sys.path)

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog, set_language
from django.contrib.auth.views import LoginView, LogoutView

from .account.urls import urlpatterns as account_urls

from menus.views import HomeView, AllUserRecentItemListView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

from machina.app import board
handler404 = 'conf.core.views.handle_404'
handler403 = 'conf.core.views.handle_404'

non_translatable_urlpatterns = [

    url(r'^i18n/$', set_language, name='set_language'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

non_translatable_urlpatterns_DEBUG = [
    # DEBUG FALSE에서 정적파일 쓰고싶으면 python manage.py runserver --insecure
    # 또는 아래 처럼
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root':settings.STATIC_ROOT}),
]

translatable_urlpatterns = [
    url(r'^jesses/', admin.site.urls),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^recent/$', AllUserRecentItemListView.as_view(), name='recent'),
    url(r'^signup/$', RegisterView.as_view(), name='signup'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^account/', include((account_urls, 'account'), namespace='account')),
    # Apps
    url(r'^forum/', include(board.urls)),
    ]

if settings.DEBUG == False and settings.LOCAL == True:
    urlpatterns = non_translatable_urlpatterns + non_translatable_urlpatterns_DEBUG + i18n_patterns(
    *translatable_urlpatterns)
else:
    urlpatterns = non_translatable_urlpatterns + i18n_patterns(
        *translatable_urlpatterns)
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
)
urlpatterns = [
    url(r'^create/$',  ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

src/profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailView, RandomProfileDetailView

urlpatterns = [
    url(r'^random/$', RandomProfileDetailView.as_view(), name='random'),
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
]

src/templates/snippets/css.html
{#{% load compile_static %}#}
{% load static %}


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" href='{% static "Custom_css/carousel.css" %}' />
{#<link rel="stylesheet" href="http://bootstrapk.com/examples/carousel/carousel.css" />#}

{#<link rel="stylesheet" href='{% static "Custom_css/Custom_less/carousel.less"|compile %}' />#}

src/templates/snippets/footer.html
<footer style="background-color: #3c3c3c; color:#FFFFFF;">
    <div class="container">
        <br>
        <div class="row">
            <div class="col-sm-3" style="text-align: center;"><h5>Copyright &copy; 2018 Shirt Geeks</h5></div>
            <div class="col-sm-4"><h5>Shirt Geeks!<p>information ~~~~~~~~~~~~~~~~~~~~~~~~ff</p></h5></div>
            <div class="col-sm-2"><h4 style="text-align: center;">SNS</h4>
                <div class="list-group">
                    <a href="#" class="list-group-item">facebook</a>
                    <a href="#" class="list-group-item">youtube</a>
                    <a href="#" class="list-group-item">twitter</a>
                </div>
            </div>
            <div class="col-sm-2"><h4 style="text-align: center;"><span class="glyphicon glyphicon-ok"></span>&nbsp;by Jesse Garcia</h4></div>
        </div>
    </div>
</footer>

src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>

src/templates/snippets/google-functions.html
{% load custom_tags %}
{% get_settings_value settings_local "LOCAL" %}
{% get_settings_value GOOGLE_ANALYTICS "GOOGLE_ANALYTICS" %}
{% get_settings_value GOOGLE_ADSENSE "GOOGLE_ADSENSE" %}

{% if settings_local == False %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ GOOGLE_ANALYTICS }}');
</script>

<!-- Google Adsense -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "{{ GOOGLE_ADSENSE }}",
    enable_page_level_ads: true
  });
</script>
{% endif %}

src/templates/snippets/js.html
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Shirt Geeks</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url "home" %}">Home</a></li>
                        <li class="{% if request.path == '/about/' %}active{% endif %}"><a href="{% url "about" %}">About</a></li>
                        <li class="{% if request.path == '/contact/' %}active{% endif %}"><a href="{% url "contact" %}">Contact</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="{% if request.path == '/restaurants/' %}active{% endif %}"><a href="{% url "restaurants:list" %}">Restaurants</a></li>
                            <li class="{% if request.path == '/items/' %}active{% endif %}"><a href="{% url "menus:list" %}">Menu Items</a></li>
                            <li class="{% if request.path == '/logout/' %}active{% endif %}"><a href="{% url "logout" %}">Logout</a></li>
                        {% else %}
                            <li class="{% if request.path == '/register/' %}active{% endif %}"><a href='{% url "register" %}'>Register</a></li>
                            <li class="{% if request.path == '/login/' %}active{% endif %}"><a href='{% url "login" %}'>Login</a></li>
                        {% endif %}

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>


<div id="baseCarousel" class="basecarousel" data-ride="carousel">
    <div class="item">
        <a class="left basecarousel-control" href="" role="">
        </a>
    </div>

</div>




{#<div class='container'>#}
{#    <div class='row text-center'>#}
{#        <div clsas='col-sm-6 col-sm-offset-3'>#}
{#            <h1>Shirt Geek</h1>#}
{#            <a href='{% url "home" %}'>Home</a>#}
{#            <a href='{% url "about" %}'>About</a>#}
{#            <a href='{% url "contact" %}'>Contact</a>#}
{#            <a href='{% url "profiles:random" %}'>Random User</a>#}
{#            {% if request.user.is_authenticated %}#}
{#                <a href='{% url "restaurants:list" %}'>Restaurants</a>#}
{#                <a href='{% url "menus:list" %}'>Menu Items</a>#}
{#                <a href='{% url "logout" %}'>Logout</a>#}
{#            {% else %}#}
{#                <a href='{% url "register" %}'>Register</a>#}
{#                <a href='{% url "login" %}'>Login</a>#}
{##}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}
{#<hr/>#}

src/templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 399</li>
</ul>